---
- name: Configure /etc/fail2ban/fail2ban.conf
  copy:
    src: fail2ban.conf
    dest: /etc/fail2ban/fail2ban.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart fail2ban

- name: Create /etc/fail2ban/fail2ban.d
  file:
    state: directory
    path: /etc/fail2ban/fail2ban.d
    owner: root
    group: root
    mode: '0755'

- name: Configure /etc/fail2ban/jail.conf
  copy:
    src: jail.conf
    dest: /etc/fail2ban/jail.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart fail2ban

- name: Create /etc/fail2ban/jail.d
  file:
    state: directory
    path: /etc/fail2ban/jail.d
    owner: root
    group: root
    mode: '0755'

- name: Configure /etc/fail2ban/jail.local
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart fail2ban
