---
- name: Converge
  hosts: all
  tasks:
    - name: "Set ansible_virtualization_type to docker"
      set_fact:
        ansible_virtualization_type: "docker"

    - name: "Sync package repositories"
      apt:
        update_cache: true

    - name: "Include stonesoupkitchen.fail2ban"
      include_role:
        name: "stonesoupkitchen.fail2ban"
